# Generated by Django 6.0.4 on 2026-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='labwork',
            name='batch',
            field=models.CharField(default='2083', max_length=10),
            preserve_default=False,
        ),
    ]
