# Generated by Django 6.0.4 on 2026-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_labwork_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
