# Generated by Django 6.0.4 on 2026-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_submission_batch_submission_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='batch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='semester',
            field=models.CharField(max_length=10),
        ),
    ]
