# Generated by Django 6.0.4 on 2026-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_submission_batch_alter_submission_roll_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
