# Generated by Django 6.0.4 on 2026-04-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_submission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labwork',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_pdfs/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Eg, Question1, Question2, etc.', max_length=100)),
                ('code_content', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission')),
            ],
        ),
    ]
