# Generated by Django 6.0.4 on 2026-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_labwork_pdf_file_alter_submission_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
