# Generated by Django 6.0.4 on 2026-05-03 04:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_submission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labwork',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
