# Generated by Django 6.0.4 on 2026-05-03 04:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_alter_labwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
