# Generated by Django 6.0.4 on 2026-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_batch_user_name_user_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
