# Generated by Django 6.0.4 on 2026-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_name_alter_user_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
    ]
