# Generated by Django 6.0.4 on 2026-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
